## 1. 학습 목표

이 절을 마치면 다음을 설명할 수 있어야 합니다.

- 벡터 정규화(normalization)가 무엇인지, 왜 필요한지 설명할 수 있다.
- L1 정규화, L2 정규화, 최대값 정규화의 개념과 차이를 구분할 수 있다.
- 코사인 유사도(cosine similarity)의 의미와 계산 방법을 설명할 수 있다.
- 정규화 전후로 코사인 유사도가 어떻게 변하는지 직접 계산할 수 있다.
- 문서 유사성 검색과 중복 검출에 정규화와 코사인 유사도를 적용할 수 있다.


## 2. 먼저 용어부터 정리

아래 용어는 이후 설명에서 계속 사용하므로 먼저 정확하게 정의합니다.

### 2.1 정규화(normalization)

**정의:** 벡터의 크기나 범위를 일정한 기준으로 변환하여 스케일을 조정하는 과정입니다.

**사용 시나리오:**
- 특징의 단위가 다를 때 (미터 vs 킬로그램)
- 머신러닝 모델의 학습 안정성 개선
- 벡터 간의 거리 또는 유사도 계산 정확성 향상
- 고차원 데이터에서 노이즈 감소

**구체적 예제:**

정규화 전 문서 벡터:
- 문서 1: [1000, 5000, 100] (큰 값)
- 문서 2: [10, 50, 1] (작은 값)

→ 스케일 차이로 인해 거리 계산 왜곡

정규화 후:
- 문서 1: [0.20, 0.98, 0.02]
- 문서 2: [0.20, 0.98, 0.02]

→ 상대적 비율이 같으면 같은 값으로 표현

코드 : Scikit-Learn을 이용한 벡터 정규화 및 코사인 유사도

In [1]:
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 2차원 구조여야 함
vectors = np.array([
    [3,4],
    [1,2]
])

l2_normalized = normalize(vectors, norm='l2')
print(f'L2 정규화 : {l2_normalized}')

sim_matrix = cosine_similarity(vectors)
sim_matrix

L2 정규화 : [[0.6        0.8       ]
 [0.4472136  0.89442719]]


array([[1.        , 0.98386991],
       [0.98386991, 1.        ]])

In [3]:
# 영화 리뷰 유사도 검색
import nltk
import ssl
from sklearn.feature_extraction.text import TfidfVectorizer
nltk.download('movie_reviews')

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\Playdata\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.


True

In [ ]:
from nltk.corpus import movie_reviews

<CategorizedPlaintextCorpusReader in 'C:\\Users\\Playdata\\AppData\\Roaming\\nltk_data\\corpora\\movie_reviews'>

In [7]:
reviews = [movie_reviews.raw(filed) for filed in movie_reviews.fileids()[:100]]
reviews[0]

'plot : two teen couples go to a church party , drink and then drive . \nthey get into an accident . \none of the guys dies , but his girlfriend continues to see him in her life , and has nightmares . \nwhat\'s the deal ? \nwatch the movie and " sorta " find out . . . \ncritique : a mind-fuck movie for the teen generation that touches on a very cool idea , but presents it in a very bad package . \nwhich is what makes this review an even harder one to write , since i generally applaud films which attempt to break the mold , mess with your head and such ( lost highway & memento ) , but there are good and bad ways of making all types of films , and these folks just didn\'t snag this one correctly . \nthey seem to have taken this pretty neat concept , but executed it terribly . \nso what are the problems with the movie ? \nwell , its main problem is that it\'s simply too jumbled . \nit starts off " normal " but then downshifts into this " fantasy " world in which you , as an audience membe

In [8]:
# TfidVectorizer 내부적으로 L2 정규화 적용
tf = TfidfVectorizer(max_features=1000)
reviews_tfidf = tf.fit_transform(reviews)
reviews_tfidf.shape # (100, 1000)

(100, 1000)

In [10]:
start = len(reviews[0]) // 2
source = reviews[0][-start:]
print(f'검색할 문서 일부')
print(source[:200]+"...")

검색할 문서 일부
taining . 
i guess the bottom line with movies like this is that you should always make sure that the audience is " into it " even before they are given the secret password to enter your world of unde...


In [12]:
# 전체문서를 TFIDF
# 대응하는 검색할 문서도 TFIDF
source_tfidf = tf.transform([source])
# 전체문서간의 행렬 TFIDF간의 코사인 유사도
sim_result_tfidf = cosine_similarity(source_tfidf, reviews_tfidf)
sim_result_tfidf

array([[0.88406165, 0.36124952, 0.45270311, 0.42028877, 0.38058249,
        0.30598688, 0.39853576, 0.29942477, 0.36906322, 0.62831918,
        0.37539675, 0.33213563, 0.4215907 , 0.43088278, 0.37670427,
        0.31094655, 0.34450787, 0.44347178, 0.43474834, 0.27192251,
        0.34663696, 0.38645913, 0.33595979, 0.47806812, 0.44178977,
        0.40064343, 0.37090871, 0.44298307, 0.45091595, 0.41070328,
        0.3864893 , 0.41174268, 0.38004554, 0.40610589, 0.37449424,
        0.42582228, 0.35392003, 0.45145317, 0.50213917, 0.3558154 ,
        0.34997828, 0.39344825, 0.3405558 , 0.34528892, 0.34029036,
        0.38725728, 0.38675477, 0.42489438, 0.34047747, 0.23211276,
        0.39898776, 0.32565626, 0.31315555, 0.39160053, 0.42712772,
        0.44911024, 0.34917012, 0.36512924, 0.26795783, 0.20051873,
        0.37672748, 0.39597293, 0.4065534 , 0.42045404, 0.38228546,
        0.46378274, 0.28061216, 0.41657267, 0.38692895, 0.39471385,
        0.42316218, 0.38254043, 0.43340025, 0.34

In [13]:
sim_result_tfidf.shape

(1, 100)

In [28]:
# 유사한 문서 상위 5
# np.argsort 항상 오름차순.. 그래서 내림차순으로 하려고 -sim_result_tfidf
top_index = np.argsort(-sim_result_tfidf).reshape(-1)[:5]
print(f'1위 인덱스 : {top_index[0]}의 유사도 점수 : {sim_result_tfidf[0][top_index[0]]}')
print(f'1위 인덱스 : {top_index[1]}의 유사도 점수 : {sim_result_tfidf[0][top_index[1]]}')

1위 인덱스 : 0의 유사도 점수 : 0.8840616506405606
1위 인덱스 : 9의 유사도 점수 : 0.628319177933569


In [31]:
sim_result_tfidf

array([[0.88406165, 0.36124952, 0.45270311, 0.42028877, 0.38058249,
        0.30598688, 0.39853576, 0.29942477, 0.36906322, 0.62831918,
        0.37539675, 0.33213563, 0.4215907 , 0.43088278, 0.37670427,
        0.31094655, 0.34450787, 0.44347178, 0.43474834, 0.27192251,
        0.34663696, 0.38645913, 0.33595979, 0.47806812, 0.44178977,
        0.40064343, 0.37090871, 0.44298307, 0.45091595, 0.41070328,
        0.3864893 , 0.41174268, 0.38004554, 0.40610589, 0.37449424,
        0.42582228, 0.35392003, 0.45145317, 0.50213917, 0.3558154 ,
        0.34997828, 0.39344825, 0.3405558 , 0.34528892, 0.34029036,
        0.38725728, 0.38675477, 0.42489438, 0.34047747, 0.23211276,
        0.39898776, 0.32565626, 0.31315555, 0.39160053, 0.42712772,
        0.44911024, 0.34917012, 0.36512924, 0.26795783, 0.20051873,
        0.37672748, 0.39597293, 0.4065534 , 0.42045404, 0.38228546,
        0.46378274, 0.28061216, 0.41657267, 0.38692895, 0.39471385,
        0.42316218, 0.38254043, 0.43340025, 0.34

In [32]:
print(f'검색할 문장 : {source}\n')
print(f'가장 유사한 문장 : {reviews[0]}\n')
print(f'두번째로 유사한 문장 : {reviews[9]}\n')

검색할 문장 : taining . 
i guess the bottom line with movies like this is that you should always make sure that the audience is " into it " even before they are given the secret password to enter your world of understanding . 
i mean , showing melissa sagemiller running away from visions for about 20 minutes throughout the movie is just plain lazy ! ! 
okay , we get it . . . there 
are people chasing her and we don't know who they are . 
do we really need to see it over and over again ? 
how about giving us different scenes offering further insight into all of the strangeness going down in the movie ? 
apparently , the studio took this film away from its director and chopped it up themselves , and it shows . 
there might've been a pretty decent teen mind-fuck movie in here somewhere , but i guess " the suits " decided that turning it into a music video with little edge , would make more sense . 
the actors are pretty good for the most part , although wes bentley just seemed to be playing th